// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsaeytpcxzigcmaunryn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzYWV5dHBjeHppZ2NtYXVucnluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjcwMzUsImV4cCI6MjA2MDc0MzAzNX0.fJ2lrQpPdGIa8YlReh1Th7owcplQRPyKABItYusH8e8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);